### ISSUE TITLE
Can't read or write in Linux

### ISSUE THREAD

**Issue by danmartinez78** [sparkfun/9DOF_Razor_IMU#12]
The board shows up as /dev/ttyACM0 but cannot be read from or written to. Arduino IDE in Linux hangs on writing data in serial monitor. The board works fine in windows.

**Comment by kruftindustries** [comment]
sudo chmod 777 /dev/ttyACM0

Look up how to put it in your upstart rules if you want the permission settings to survive a restart

**Comment by bboyho** [comment]
Hi,

If the board works with a Windows but not on a Linux, it may be due to your permissions as kruftindustries stated. I am not sure what version of the Arduino IDE you are using. Try reinstalling the Arduino IDE or using a different version if you have not already. Looking briefly at the Arduino.cc forums and StackExchange: Arduino, this can also help when data "freezes" or "hangs" as data is sent to the Arduino serial monitor. 

Since there has not been a response, I assume that the issue was resolved. We can re-open this issue if you are still having problems. 

PS: Thanks @kruftindustries for posting! =)
