### ISSUE TITLE
Not able to compile SparkFunMPU9250-DMP.cpp

### ISSUE THREAD

**Issue by MarcoWerth** [sparkfun/9DOF_Razor_IMU#19]
Hi,
tried to compile razor firmware in arduino IDE. 
Included library SparkFunMPU9250-DMP.cpp from this git directory. 

But during compilation I receive several errors.

> MPU9250DMP/SparkFunMPU9250-DMP.cpp.o: In Funktion MPU9250_DMP::dmpSetOrientation(signed char const*)':
> /home/marco/sketchbook/libraries/MPU9250DMP/SparkFunMPU9250-DMP.cpp:532: Nicht definierter Verweis auf `mpu_set_lpf'
> /home/marco/sketchbook/libraries/MPU9250DMP/SparkFunMPU9250-DMP.cpp:532: Nicht definierter Verweis auf "mpu_set_sample_rate"
> /home/marco/sketchbook/libraries/MPU9250DMP/SparkFunMPU9250-DMP.cpp:532: Nicht definierter Verweis auf "mpu_set_compass_sample_rate"
> /home/marco/sketchbook/libraries/MPU9250DMP/SparkFunMPU9250-DMP.cpp:532: Nicht definierter Verweis auf "mpu_get_gyro_sens"
> /home/marco/sketchbook/libraries/MPU9250DMP/SparkFunMPU9250-DMP.cpp:532: Nicht definierter Verweis auf "mpu_set_gyro_fsr"
> /home/marco/sketchbook/libraries/MPU9250DMP/SparkFunMPU9250-DMP.cpp:532: Nicht definierter Verweis auf "mpu_get_accel_sens"
> ....
> collect2: error: ld returned 1 exit status

Any advise?

**Comment by bboyho** [comment]
Hi,

It looks like the Arduino library's path is not correct. The Arduino IDE probably does not understand the functions and variables that it is referring to when you are compiling the example code since it is not able to find the associated files.  Make sure that you installed the library correctly. If you have not installed an Arduino library before, try looking at this tutorial using the Arduino Library Manager [ [https://learn.sparkfun.com/tutorials/installing-an-arduino-library#using-the-arduino-library-manager](https://learn.sparkfun.com/tutorials/installing-an-arduino-library#using-the-arduino-library-manager) ]. 

Otherwise, try using a different Arduino IDE version or computer to see if the code is able to compile.
